version: "3.9"
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: metabase_db
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  metabase_db:
    image: postgres:16
    container_name: metabase_db
    hostname: metabase_db
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./metabase-db-data:/var/lib/postgresql/data
    networks:
      - metanet1

  delivery_db:
    image: postgres:16
    container_name: delivery_db
    hostname: delivery_db
    environment:
      POSTGRES_USER: delivery_user
      POSTGRES_DB: delivery_food_db
      POSTGRES_PASSWORD: delivery_password
    ports:
      - "5433:5432"
    volumes:
      - ./delivery-db-data:/var/lib/postgresql/data
    networks:
      - metanet1

networks:
  metanet1:
    driver: bridge
